import type { WmsTrackerTask } from "@/lib/wms-tracker-types";

export const wmsTrackerSeedTasks: WmsTrackerTask[] = [
  {
    "id": "seed-tracker-row-3",
    "sourceKey": "sheet-row-3",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Generación de Usarios de Operadores",
    "taskType": "Funcion SGL",
    "description": "Definir y generar usuarios de operadores y Supervisores.",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Esperando que se definan las pruebas y los operadores para realizar los usuarios finales, mas cerca a fecha de lanzamiento.",
    "position": 0
  },
  {
    "id": "seed-tracker-row-4",
    "sourceKey": "sheet-row-4",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Dispoción de Handheld para Operadores",
    "taskType": "Herramientas",
    "description": "Verificar que todos los operadores cuenten con una Handheld para trabajar",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Disponemos de las handheld, pero estamos esperando a que avance mas el desarrollo funcional del sistema",
    "position": 1
  },
  {
    "id": "seed-tracker-row-5",
    "sourceKey": "sheet-row-5",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Permisos Operacionales ",
    "taskType": "Funcion SGL",
    "description": "Definir y aplicar en sistema los permisos operacionales de los usuarios según el Area y Rol.",
    "priority": 4,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-25",
    "response": "Esperando que se definan las pruebas y los operadores para definir permisos, mas cerca a fecha de lanzamiento.",
    "position": 2
  },
  {
    "id": "seed-tracker-row-6",
    "sourceKey": "sheet-row-6",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Carga correcta de Articulos",
    "taskType": "Funcion SGL",
    "description": "Que todos los articulos estén cargados correctamente, con su Codigo de Barras, Unidad de venta y SKU correctos. ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Los articulos se encuentran cargados según la bajada de ERP. Resta asociarle la Unidad de Venta, y definir las Unidades x Bulto (Cant. x caja master)",
    "position": 3
  },
  {
    "id": "seed-tracker-row-7",
    "sourceKey": "sheet-row-7",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Vinculación de Impresoras a Sistema",
    "taskType": "Funcion SGL",
    "description": "Vinculación de impresoras que se utilizarán en el proceso con SGL.",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 4
  },
  {
    "id": "seed-tracker-row-8",
    "sourceKey": "sheet-row-8",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Etiqueta de Impresora",
    "taskType": "Funcion SGL",
    "description": "Debemos tener las etiquetas de escaneo de las impresoras puestas en las impresoras.",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 5
  },
  {
    "id": "seed-tracker-row-9",
    "sourceKey": "sheet-row-9",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Pruebas con etiqueta de las impresoras",
    "taskType": "Pruebas",
    "description": "Realizar pruebas para verificar las etiquetas de impresora y las etiquetas que imprimen las mismas para el proceso Verificar procedimiento de control y carga de contenedores .",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "No están habilitadas las etiquetas de impresoras, ni la impresión de las mismas, por lo cual por el momento no podemos realizar pruebas",
    "position": 6
  },
  {
    "id": "seed-tracker-row-10",
    "sourceKey": "sheet-row-10",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Reimpresión de etiquetas de contenedor",
    "taskType": "Funcion SGL",
    "description": "Verificar funcionamiento de la reimpresión de etiquetas.",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Actualmente la interfaz no funciona en el sistema. No imprime con el mismo formato.",
    "position": 7
  },
  {
    "id": "seed-tracker-row-11",
    "sourceKey": "sheet-row-11",
    "process": "GENERALES",
    "taskDate": "2026-07-28",
    "title": "Proceso de Garantias",
    "taskType": "Funcion SGL",
    "description": "Tener definido como se realizará el proceso de garantias dentro del sistema SGL. En caso de que se precise, sumar item para el equipo de SGL",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "El proceso de Garantias no se contempla por dentro del Sistema SGL. Ver como se definirá el proceso con el sistema y BAM",
    "position": 8
  },
  {
    "id": "seed-tracker-row-12",
    "sourceKey": "sheet-row-12",
    "process": "GENERALES",
    "taskDate": "2026-07-28",
    "title": "Asignar Codigo para Caja Master",
    "taskType": "Funcion SGL",
    "description": "Ver función en sistema para asignar un Codigo de Barras a un articulo para cajas Master",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Verificado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": true,
    "responseDate": "2026-07-28",
    "response": "Función de asignar codigos en sistema realizado y verificado. Video explicativo de proceso en DRIVE.",
    "position": 9
  },
  {
    "id": "seed-tracker-row-13",
    "sourceKey": "sheet-row-13",
    "process": "GENERALES",
    "taskDate": "2026-07-28",
    "title": "Definir Codigos de Caja Master",
    "taskType": "LayOut",
    "description": "Definir en que Articulos se van a etiquetas caja master y que codigo se le va a asignar.",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-28",
    "response": "Actualmente se está revisando. Ver casos según unidad x Caja Master y Und. Venta",
    "position": 10
  },
  {
    "id": "seed-tracker-row-14",
    "sourceKey": "sheet-row-14",
    "process": "GENERALES",
    "taskDate": "2026-07-28",
    "title": "Formato de carga masiva para codigos de Caja Master",
    "taskType": "Funcion SGL",
    "description": "Tener un formato y/o procedimiento de carga masiva de los codigo de barra asociados a la caja master de los articulos",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 11
  },
  {
    "id": "seed-tracker-row-15",
    "sourceKey": "sheet-row-15",
    "process": "GENERALES",
    "taskDate": "2026-08-20",
    "title": "Sincronización BAM y WMS ",
    "taskType": "Funcion SGL",
    "description": "Realizar la vinculación de SGLWMS a BAMID. Verificar sincronización de STOCK y actualización de datos",
    "priority": 1,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-02",
    "response": "Ya esta vindulado BAMTEST con SGLTEST, pudiendo realizar pedidos y pruebas",
    "position": 12
  },
  {
    "id": "seed-tracker-row-16",
    "sourceKey": "sheet-row-16",
    "process": "GENERALES",
    "taskDate": "2026-07-24",
    "title": "Codigo de Barra de articulos",
    "taskType": "Herramientas",
    "description": "Debemos disponibilizar de los articulos debidamente etiquetados para la lectura del sistema",
    "priority": 1,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Se está realizando un proceso de Re-Etiquetado para todos los articulos con mas salida. En caso de que no se llegue con los plazos de tiempo, se debe proponer otro proceso para realizar la lecturade los articulos.",
    "position": 13
  },
  {
    "id": "seed-tracker-row-17",
    "sourceKey": "sheet-row-17",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Impresora de etiquetas",
    "taskType": "Herramientas",
    "description": "Debemos de disponibilizar de una impresora en el sector para realizar la impresion de etiquetas de contenedor ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Verificado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": true,
    "responseDate": "2026-07-24",
    "response": "Contamos con la Impresora INDUSTRIAL en el sector de Recepción",
    "position": 14
  },
  {
    "id": "seed-tracker-row-18",
    "sourceKey": "sheet-row-18",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Programación de impresoras SGL",
    "taskType": "Funcion SGL",
    "description": "Debemos tener conectada/vinculada la impresora al sistema.",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 15
  },
  {
    "id": "seed-tracker-row-19",
    "sourceKey": "sheet-row-19",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Creación de Docks recepción",
    "taskType": "LayOut",
    "description": "Disponer de los docks armados referente a la las posiciones de Control, Nacional e Importado",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Esperando el avance de las pruebas e interfacez para definir espacio fisico de docks, y posteriormente crearlos en Sistema",
    "position": 16
  },
  {
    "id": "seed-tracker-row-20",
    "sourceKey": "sheet-row-20",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Etiquetas de Dock",
    "taskType": "Funcion SGL",
    "description": "Tener la generación de etiquetas de DOCK",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 17
  },
  {
    "id": "seed-tracker-row-21",
    "sourceKey": "sheet-row-21",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Colocación de etiquetas Dock",
    "taskType": "LayOut",
    "description": "Definir y colocar etiquetas de DOCK en las posiciones correspondientes.",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "No está disponible la opción de generación de etiquetas de DOCK, por ende no podemos imprimirlos ni generar pruebas",
    "position": 18
  },
  {
    "id": "seed-tracker-row-22",
    "sourceKey": "sheet-row-22",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Generación Instructivos operaciones",
    "taskType": "Entrenamiento",
    "description": "Instructivo operacional para personal operativo del sector",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Instructivo Operacional de Recepción realizado",
    "position": 19
  },
  {
    "id": "seed-tracker-row-23",
    "sourceKey": "sheet-row-23",
    "process": "RECEPCIÓN",
    "taskDate": "2026-08-05",
    "title": "Ubicación de la colocación de etiquetas de contenedor",
    "taskType": "LayOut",
    "description": "Tanto las cajas master, como los medios que se designen como CONTENEDOR y a su vez que sean guardados como CONTENEDOR, deben de tener una zona ESTANDARIZADA de ubicación de etiqueta, para la posterior lectura en los traslado o pickeos",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 20
  },
  {
    "id": "seed-tracker-row-24",
    "sourceKey": "sheet-row-24",
    "process": "RECEPCIÓN",
    "taskDate": "2026-08-13",
    "title": "Definir tipo y forma de recepcionar los ingresos desde sistema",
    "taskType": "LayOut",
    "description": "Estandarizar las formas de recepcionar la mercaderia, tipo de recepción, etiquetas de contenedores y controles de calidad ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-08-13",
    "response": "Realizando pruebas desde sistema para definir criterios y maneras de recepcionar la mercaderia enSGL",
    "position": 21
  },
  {
    "id": "seed-tracker-row-25",
    "sourceKey": "sheet-row-25",
    "process": "RECEPCIÓN",
    "taskDate": "2026-08-14",
    "title": "Entrenamiento en lectura de etiquetas",
    "taskType": "Funcion SGL",
    "description": "Al momento de Escanear el N° Contenedor, es posible equivocarse y leer el CB del articulo, el sistema toma OK y traslada el error. Entrenamiento a los operarios para la ectura y verificación en HH (Cont., Art., Posiciones)",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 22
  },
  {
    "id": "seed-tracker-row-26",
    "sourceKey": "sheet-row-26",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Operadores",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento de operadores de Recepción. Tipo de Ingreso (Contenedor/Multiarticulo), utilización de sistema, traslados y colocación de etiquetas de contenedor. Entrenamiento de sistema y proceso logistico fisico. Generación de .txt (Recepción Nacionall)",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Se sigue avanzando con el entrenamiento del personal de recepción y stock con las herramientas que se tienen. Generación de instructivos operaciones para personal  LINK IT.",
    "position": 23
  },
  {
    "id": "seed-tracker-row-27",
    "sourceKey": "sheet-row-27",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Supervisor",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento a supervisor sobre herramientas de gestión, visibilidad de pedidos, controles ciegos y asignaciones ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Se sigue avanzando con el entrenamiento del personal con las herramientas que tenemos.",
    "position": 24
  },
  {
    "id": "seed-tracker-row-28",
    "sourceKey": "sheet-row-28",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-28",
    "title": "Prueba de circuito completo",
    "taskType": "Pruebas",
    "description": "Verificar un circuito completo de proceso de recepción. Verficando generación de etiquetas de cont. etiquetas de dock. y todos los procesos acordes.",
    "priority": 4,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-28",
    "response": "A la espera de terminar todos los ajustes de proceso",
    "position": 25
  },
  {
    "id": "seed-tracker-row-29",
    "sourceKey": "sheet-row-29",
    "process": "RECEPCIÓN",
    "taskDate": "2026-08-03",
    "title": "Posición SobreStock articulos Nacionales",
    "taskType": "LayOut",
    "description": "Actualmente el sobrestock de los articulos Nacionales se encuentran ubicados en el area de recepción. Definir correctamente ese proceso y si es necesario crear una posición en SGL referente a ALMACEN (Nacional) en el area de Recepción",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 26
  },
  {
    "id": "seed-tracker-row-30",
    "sourceKey": "sheet-row-30",
    "process": "RECEPCIÓN",
    "taskDate": "2026-07-24",
    "title": "Definición de proceso de Etiquetado a Cajas Master",
    "taskType": "Entrenamiento",
    "description": "Proceso de etiquetado en ingreso de caja master con etiqueta de Contenedor.",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-24",
    "response": "Esta está realizando el procecimiento de etiquetado. Cuando avance mas el sistema se harán pruebas",
    "position": 27
  },
  {
    "id": "seed-tracker-row-31",
    "sourceKey": "sheet-row-31",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Funcionalidad de guardado Multiple",
    "taskType": "Funcion SGL",
    "description": "Función de GUARDADO MULTIPLE para almacenamiento de caja master. Esta función sirve para almacenar simultaneamente varios contenedores. Queda pendiente de función",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-02",
    "response": "Actualmente se está evualuando si esta funcion la utilizaremos o no, según si etiquetamos o no caja master en recepción. Estamos en la definición de este parametro.",
    "position": 28
  },
  {
    "id": "seed-tracker-row-32",
    "sourceKey": "sheet-row-32",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Ubicaciones",
    "taskType": "Funcion SGL",
    "description": "Definición de ubicaciones y sus parametros (Dimensiones, Profundidad, TIPO, estado) de cada posición",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Ubicaciones creadas. Resta terminar de parametrizar ubicaciones (Profundidades, Tipo, SKU permitidos) a la espera de Inventario)",
    "position": 29
  },
  {
    "id": "seed-tracker-row-33",
    "sourceKey": "sheet-row-33",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-30",
    "title": "Profundidades según contenedores en Posición",
    "taskType": "Funcion SGL",
    "description": "Verificar cada posición y acomodar parametros de sistema. Para los casos donde haya posiciones fijas (como gavetas, cajas o canastos) asignar el equivalente de Posiciones en esa ubicación.\nAcomodar parametros según cada ubicación ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Se está revisando. Resta hacer el relevamiento mas cerca al lanzamiento.",
    "position": 30
  },
  {
    "id": "seed-tracker-row-34",
    "sourceKey": "sheet-row-34",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Etiqueta de ubicaciones",
    "taskType": "LayOut",
    "description": "Todas las ubicaciones deben tener su codigo de barras asociado colocado fisicamente. Las ubicaciones que no están en rack también.",
    "priority": 1,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Se sigue avanzan con el etiquetado de las ubicaciones.",
    "position": 31
  },
  {
    "id": "seed-tracker-row-35",
    "sourceKey": "sheet-row-35",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Zonificación de articulos",
    "taskType": "Funcion SGL",
    "description": "Definir Zonificacion de articulos según tipo y familia, y realizar la carga masiva a Sistema para hacer la agrupación en proceso de guardado  guardao, verificar punto.",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Queda pendiente realizar la carga masiva de datos para zonificar articulos según corresponda.",
    "position": 32
  },
  {
    "id": "seed-tracker-row-36",
    "sourceKey": "sheet-row-36",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Generación Instructivos operaciones",
    "taskType": "Entrenamiento",
    "description": "Instructivo operacional para el sector de Stock",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Instructivo Operacional de Stock realizado . IT04 - MOVIMIENTO DE STOCK (GUARDADO - ABASTECIMIENTO)",
    "position": 33
  },
  {
    "id": "seed-tracker-row-37",
    "sourceKey": "sheet-row-37",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Operadores",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento a personal. Tipo de Guardado (Bulto, Contenedor), lectura y movmiento de DOCKs, Proceso de guardado de material",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Se sigue avanzando con el entrenamiento del personal de recepción y stock con las herramientas que se tienen. Generación de instructivos operaciones para personal  LINK IT.",
    "position": 34
  },
  {
    "id": "seed-tracker-row-38",
    "sourceKey": "sheet-row-38",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-08-13",
    "title": "Ubicacion de cajas",
    "taskType": "LayOut",
    "description": "Definir de que forma se van a almacenar las cajas en los racks para posteriormente dejar las etiquetas a la vista",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 35
  },
  {
    "id": "seed-tracker-row-39",
    "sourceKey": "sheet-row-39",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Supervisor",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento de funciones ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Se sigue avanzando con el entrenamiento del personal con las herramientas que tenemos.",
    "position": 36
  },
  {
    "id": "seed-tracker-row-40",
    "sourceKey": "sheet-row-40",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Abastecimiento por Ola",
    "taskType": "Funcion SGL",
    "description": "Función de orden de Reabastecimiento según parametros. No tenemos información de su uso.",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 37
  },
  {
    "id": "seed-tracker-row-41",
    "sourceKey": "sheet-row-41",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Generación de Inventario",
    "taskType": "Funcion SGL",
    "description": "Funcion para crear Inventarios. No tenemos información ni permisos para su uso",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 38
  },
  {
    "id": "seed-tracker-row-42",
    "sourceKey": "sheet-row-42",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-08-04",
    "title": "Selección de Contenedor en Guardado x Bulto",
    "taskType": "Funcion SGL",
    "description": "Durante el guardado x bulto, al momento de seleccionar una posición, en caso de que tenga uno o varios contenedores, se depliega un menú seleccionable para elegir en cual se va a dejar la mercadería. Esta opción es propensa al error humano porque puede seleccionar cualquier contenedor sin saber si esta fisicamente o si es el correcto (articulos). \nDebemos tener un apartado de escanear el contenedor donde se posicione y no seleccionarlo",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-02",
    "response": "Actualmente se está evualuando si esta funcion la utilizaremos o no, según si etiquetamos o no caja master en recepción. Estamos en la definición de este parametro.",
    "position": 39
  },
  {
    "id": "seed-tracker-row-43",
    "sourceKey": "sheet-row-43",
    "process": "GUARDADO / STOCK",
    "taskDate": "2026-07-24",
    "title": "Solicitud de Re Abastecimiento",
    "taskType": "Funcion SGL",
    "description": "Verificar funcionamento de ordenes de ReAbastecimiento (x Demanda / x Hueco) desde la HH",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-28",
    "response": "Se estan realizando pruebas, pero van a ser mas Representativas cuanto se cuente con mas Stock cargado en sistema y con la función de Ola de Abastecimiento funcionando.",
    "position": 40
  },
  {
    "id": "seed-tracker-row-44",
    "sourceKey": "sheet-row-44",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Impresora de etiquetas",
    "taskType": "Herramientas",
    "description": "Debemos de disponibilizar de una impresora en el sector para realizar la impresion de etiquetas de contenedor ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Verificado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": true,
    "responseDate": "2026-07-27",
    "response": "Tenemos impresoras ZEBRA en el sector de Preparación para realizar impresiones",
    "position": 41
  },
  {
    "id": "seed-tracker-row-45",
    "sourceKey": "sheet-row-45",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Grupo Picking",
    "taskType": "Funcion SGL",
    "description": "Entender concepto y utilidad. Definir si es aplicable, y como avanzar.",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 42
  },
  {
    "id": "seed-tracker-row-46",
    "sourceKey": "sheet-row-46",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Programación de impresoras SGL",
    "taskType": "Funcion SGL",
    "description": "Debemos tener conectada/vinculada la impresora al sistema.",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 43
  },
  {
    "id": "seed-tracker-row-47",
    "sourceKey": "sheet-row-47",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Generación Instructivos operaciones",
    "taskType": "Entrenamiento",
    "description": "Instructivo operacional para el sector de Stock",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Instructivo operacional realizado y entregado al sector",
    "position": 44
  },
  {
    "id": "seed-tracker-row-48",
    "sourceKey": "sheet-row-48",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Operadores",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento operacional referente a la utilización de HH, traslado a ubicaciones, pickeo de materia, cierre de contenedor, traslado de material ",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Entrenamiento constante hacia el sector ",
    "position": 45
  },
  {
    "id": "seed-tracker-row-49",
    "sourceKey": "sheet-row-49",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Supervisor",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento sobre confirmación de pedidos, verficiación de stock, asignaciones, control en vivo de pedidos.",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Entrenamiento constante hacia el sector ",
    "position": 46
  },
  {
    "id": "seed-tracker-row-50",
    "sourceKey": "sheet-row-50",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Definición de tope de lineas por pedido",
    "taskType": "Funcion SGL",
    "description": "Función para que una OP se divida cuando llegue a un tope de lineas definido. ",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Actualmente no tenemos esa función",
    "position": 47
  },
  {
    "id": "seed-tracker-row-51",
    "sourceKey": "sheet-row-51",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "OP con varios contenedores",
    "taskType": "Funcion SGL",
    "description": "Actualmente durante el proceso de picking al momento de cerrar un contenendor de una OP te obiliga a trasladarlo una Isla de control, lo cual frena el proceso de picking. Precisamos que está función se mejore para acumular contenedores, o definir otro metodo de pickeo.",
    "priority": 1,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-01",
    "response": "Punto tomado por el equipo de SGL",
    "position": 48
  },
  {
    "id": "seed-tracker-row-52",
    "sourceKey": "sheet-row-52",
    "process": "PICKING",
    "taskDate": "2026-07-28",
    "title": "Transformación de Kits",
    "taskType": "Funcion SGL",
    "description": "Contar con opción para transformar unidades en Kits dentro del sisetema. En caso de no ser así, definir proceso alterno para este tipo de producto.",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-01",
    "response": "En esta instancia se preveé que la transformación de KIT pase para la segunda etapa de la implementación del sistema",
    "position": 49
  },
  {
    "id": "seed-tracker-row-53",
    "sourceKey": "sheet-row-53",
    "process": "PICKING",
    "taskDate": "2026-07-24",
    "title": "Solicitud de ReAbastecimiento",
    "taskType": "Funcion SGL",
    "description": "Verificar procedimientos de reabastecimiento de sistema. Solicitud de ReAbastecimiento x dem. y x hueco",
    "priority": 4,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "No contamos con los datos en sistema para realizar esta prueba. Vamos a esperar a mayor caudal de datos para realizar pruebas.",
    "position": 50
  },
  {
    "id": "seed-tracker-row-54",
    "sourceKey": "sheet-row-54",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Verificar cierre de contenedor",
    "taskType": "Funcion SGL",
    "description": "En la interfaz de SGL, actualmente si se cierra el contenedor que se está controlando el mismo sistema intenta cerrar forzadamente el pedido añadiendo un bulto y controlando articulos que no se controlador fisicamente.",
    "priority": 1,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-01",
    "response": "Punto tomado por el equipo de SGL",
    "position": 51
  },
  {
    "id": "seed-tracker-row-55",
    "sourceKey": "sheet-row-55",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Impresoras de etiquetas",
    "taskType": "Herramientas",
    "description": "Definir que impresoras se van a utilizar para las imprimirar las etiquetas de bulto y donde se van a ubicar",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "No Definido.",
    "position": 52
  },
  {
    "id": "seed-tracker-row-56",
    "sourceKey": "sheet-row-56",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Control de Isla por Unidad y por Cantidad",
    "taskType": "Funcion SGL",
    "description": "Generar la función para Isla de Control donde se pueda controlar por contenedor o por Unidad. De esta manera habilitando la lectura individual de cada articulo, y en los casos de varias cajas master o pedidos grandes realizar el control escribiendo las cantidades.",
    "priority": 1,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-01",
    "response": "Se está definiendo si utilizaremos un solo metodo en sistema o si precisamos ambas condiciones en el sistema",
    "position": 53
  },
  {
    "id": "seed-tracker-row-57",
    "sourceKey": "sheet-row-57",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Definir Mesas de Control",
    "taskType": "LayOut",
    "description": "Definir las mesas de control fisicamente. (Tamaño de mesa, tipo de control, cantidades)",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "A la espera de definir LayOut",
    "position": 54
  },
  {
    "id": "seed-tracker-row-58",
    "sourceKey": "sheet-row-58",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Crear mesas de control en sistema",
    "taskType": "Funcion SGL",
    "description": "Generación en sistema de las mesas que se utilizarán en el proceso",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "A la espera de definir LayOut",
    "position": 55
  },
  {
    "id": "seed-tracker-row-59",
    "sourceKey": "sheet-row-59",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Definir nomenclatura de Isla de Control",
    "taskType": "LayOut",
    "description": "Definir nomenclatura de lectura de etiqueta de Isla de control. Actualmente se está leyendo un numero (1 , 2, 3)",
    "priority": 4,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "A la espera de definir LayOut",
    "position": 56
  },
  {
    "id": "seed-tracker-row-60",
    "sourceKey": "sheet-row-60",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Generación de etiqueta de Mesa",
    "taskType": "Funcion SGL",
    "description": "Generar la etiqueta de cada isla de control",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 57
  },
  {
    "id": "seed-tracker-row-61",
    "sourceKey": "sheet-row-61",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Colocación de etiquetas de Mesa",
    "taskType": "LayOut",
    "description": "Colocar a cada mesa asignada la etiqueta de la Isla de Control que le corresponda. Verificar su funcionamiento",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "No tenemos las etiquetas de IC generadas.",
    "position": 58
  },
  {
    "id": "seed-tracker-row-62",
    "sourceKey": "sheet-row-62",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Generación Instructivos operaciones",
    "taskType": "Entrenamiento",
    "description": "Instructivo operacional para el sector de Stock",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Instructivo Realizado y controlado diariamente",
    "position": 59
  },
  {
    "id": "seed-tracker-row-63",
    "sourceKey": "sheet-row-63",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Operadores",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento operacional. Forma de control en IC, tipo de control, Confirmación de control, impresión de bultos y traslado de material",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Entrenamiento constante hacia el sector ",
    "position": 60
  },
  {
    "id": "seed-tracker-row-64",
    "sourceKey": "sheet-row-64",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Supervisor",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento a Referente del sector. Herramientas de gestion y supervisión, seguimientos de procesos y extracción de reportes",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Entrenamiento constante hacia el sector ",
    "position": 61
  },
  {
    "id": "seed-tracker-row-65",
    "sourceKey": "sheet-row-65",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Función de lectura. Traslado a Dock",
    "taskType": "Funcion SGL",
    "description": "Verificar función post IC que solicite el escaneo de DOCK para confirmar el traslado de los bultos.",
    "priority": 2,
    "responsible": "Equipo SGL",
    "status": "Verificado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": true,
    "responseDate": "2026-07-27",
    "response": "No se utilizará esta función. Se retira FRENTE DE CARGA del sistema debido a al tipo de control que se está haciendo",
    "position": 62
  },
  {
    "id": "seed-tracker-row-66",
    "sourceKey": "sheet-row-66",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Visualización de problemas de IC",
    "taskType": "Funcion SGL",
    "description": "Función para visualizar los errores que aparecen en el control de islta (Lectura incorrecta, de mas, de menos, articulo incrrecto, etc.). Actualmente no está la función",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-02",
    "response": "Punto tomado por el equipo de SGL Tenemos una posibilidad de visualizar desde SITUACION DE ISLA DE CONTROL",
    "position": 63
  },
  {
    "id": "seed-tracker-row-67",
    "sourceKey": "sheet-row-67",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Generación de Etiquetas de Bulto",
    "taskType": "Funcion SGL",
    "description": "Generación e impresión de etiquetas de Bulto posterior a control en Isla",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-02",
    "response": "El sistema genera las etiquetas correctamente. Resta verificar la impresión de las eitquetas de forma fisica con una impresora y la lectura en el despacho",
    "position": 64
  },
  {
    "id": "seed-tracker-row-68",
    "sourceKey": "sheet-row-68",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Verificar etiquetas de bulto",
    "taskType": "Funcion SGL",
    "description": "Verificar correcta lectura de etiquetas de bulto",
    "priority": 4,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "A la espera de Sistema. No genera CB.",
    "position": 65
  },
  {
    "id": "seed-tracker-row-69",
    "sourceKey": "sheet-row-69",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Isla de Control para Supervisores",
    "taskType": "Funcion SGL",
    "description": "Verificar funcionamiento de Supervisión y control de las islas generadas",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Actualmente no funciona.",
    "position": 66
  },
  {
    "id": "seed-tracker-row-70",
    "sourceKey": "sheet-row-70",
    "process": "ISLA DE CONTROL",
    "taskDate": "2026-07-24",
    "title": "Generación de Docks de Salida",
    "taskType": "LayOut",
    "description": "Generación de DOCK de salida (CABA, Norte, Expreso, etc.)",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "A la espera de Definir Docks (Fisco y Sistema) por parte del Equipo Logistica, y de la generación de etiquetas por parte del equipo de SGL",
    "position": 67
  },
  {
    "id": "seed-tracker-row-71",
    "sourceKey": "sheet-row-71",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Parametros de Transporte y Chofer",
    "taskType": "Funcion SGL",
    "description": "Dentro del sistema se debe definir todos los datos referentes a los Transportes que se utilicen, Transportistas y choferes, Con el fin de realizar la generación de viaje con los datos correspondientes",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Todavia no tenemos definido esos datos y parametros, se realizará la carga masiva cuando estemos cerca del lanzamiento.",
    "position": 68
  },
  {
    "id": "seed-tracker-row-72",
    "sourceKey": "sheet-row-72",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Despacho  Parcial",
    "taskType": "Funcion SGL",
    "description": "Función para realizar despacho parcial de una OP. en los casos donde todos los contenedores una OP no se puedan despachar. O sugerencia de como realizar este proceso.",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 69
  },
  {
    "id": "seed-tracker-row-73",
    "sourceKey": "sheet-row-73",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Depacho por contenedor",
    "taskType": "Funcion SGL",
    "description": "Definir si se utilizará, y como, esta función. Ya que solo funciona si se controla en IC por cont. (No se puede). Actualmente en caso de que IC dejé un pedido en un pallet completo, en Despacho se debe desarmar pallet para leer los CB de Bultos",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 70
  },
  {
    "id": "seed-tracker-row-74",
    "sourceKey": "sheet-row-74",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-08-06",
    "title": "Remisión obligatoria previao a generación de viaje",
    "taskType": "LayOut",
    "description": "Definir si es NECESARIO poder hacer GENERACIÓN de VIAJES sin remito. Actualmente no se puede generar viajes a pedidos que no fueron remitidos y controlados previamente",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 71
  },
  {
    "id": "seed-tracker-row-75",
    "sourceKey": "sheet-row-75",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Comunicación de Interfaces WMS - Persat",
    "taskType": "Funcion SGL",
    "description": "Funcionamiento de Interfaces WMS - Persat.",
    "priority": 1,
    "responsible": "Equipo SGL",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-09-01",
    "response": "Punto tomado por el equipo de SGL",
    "position": 72
  },
  {
    "id": "seed-tracker-row-76",
    "sourceKey": "sheet-row-76",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Generación Instructivos operaciones",
    "taskType": "Entrenamiento",
    "description": "Instructivo operacional para el sector de experidicón ",
    "priority": 3,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Instructivo de Remito y Despacho realizado",
    "position": 73
  },
  {
    "id": "seed-tracker-row-77",
    "sourceKey": "sheet-row-77",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Operadores",
    "taskType": "Entrenamiento",
    "description": "Entranmiento administrativo. Generación de viaje, Seguimiento de viaje, Confirmación de salida,",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizando",
    "isDoing": true,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Se está entrenando al personal con las herramientas que tenemos",
    "position": 74
  },
  {
    "id": "seed-tracker-row-78",
    "sourceKey": "sheet-row-78",
    "process": "EXPEDICIÓN",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Jefe de sector",
    "taskType": "Entrenamiento",
    "description": "",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-27",
    "response": "Actualmente no tenemos vinculado PERSAT en sistema, por lo cual no es posible tener pruebas representativas para entrenamiento.",
    "position": 75
  },
  {
    "id": "seed-tracker-row-79",
    "sourceKey": "sheet-row-79",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-24",
    "title": "Verificar los permisos de ajuste y NoDisponibildiad",
    "taskType": "Funcion SGL",
    "description": "Verificar que no todos los Uusarios Operaciones cuenten con la posiblidad de ajustar un contenedor. Administrar permisos",
    "priority": 3,
    "responsible": "Equipo SGL",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "",
    "response": "",
    "position": 76
  },
  {
    "id": "seed-tracker-row-80",
    "sourceKey": "sheet-row-80",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-24",
    "title": "Definición de motivos de NoDisponibiliad de contenedor",
    "taskType": "Funcion SGL",
    "description": "Definir dentro del sistema los motivos prefijados de NoDisponibilidad de un contenedor",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Espera de avanzar mas con el sistema y alineas criteros para determinar motivos",
    "position": 77
  },
  {
    "id": "seed-tracker-row-81",
    "sourceKey": "sheet-row-81",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-24",
    "title": "Definición de motivos de ajuste de contenedores ",
    "taskType": "Funcion SGL",
    "description": "Definir dentro del sistema los motivos de Ajustes de un contenedor",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Espera de avanzar mas con el sistema y alineas criteros para determinar motivos",
    "position": 78
  },
  {
    "id": "seed-tracker-row-82",
    "sourceKey": "sheet-row-82",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-30",
    "title": "Definición de proceso de Revisión en sistema",
    "taskType": "LayOut",
    "description": "Proceso Definido para el Area de revisión. Ubicaciones (En puntera y Sector Auditoria), traslados, movimiento y flujo operacional. Disponibilidad de contenedores",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Todavía no se vió el punto",
    "position": 79
  },
  {
    "id": "seed-tracker-row-83",
    "sourceKey": "sheet-row-83",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-30",
    "title": "Definición de proceso de limpieza de calle",
    "taskType": "LayOut",
    "description": "Como se va a trabajar el proceso de Limpieza de Calles con el Sistema. Movimientos, contenedores y flujo operacional. Disponibilidad de contenedores",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Todavía no se vió el punto",
    "position": 80
  },
  {
    "id": "seed-tracker-row-84",
    "sourceKey": "sheet-row-84",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-30",
    "title": "Definición de proceso de Sobrantes en sistema",
    "taskType": "LayOut",
    "description": "Proceso de Sobrantes por sistema. Utilización de ubicaciones, contenedores, movimientos o si se trabaja por fuera de sistema. Disponibilidad de contenedores",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Todavía no se vió el punto",
    "position": 81
  },
  {
    "id": "seed-tracker-row-85",
    "sourceKey": "sheet-row-85",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-24",
    "title": "Generación Instructivos operaciones Auditorias",
    "taskType": "Entrenamiento",
    "description": "Definición y estandarización de proceso de Auditorias",
    "priority": 2,
    "responsible": "Logistica",
    "status": "Realizado",
    "isDoing": true,
    "isCompleted": true,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Se completó el Instructivo con la información hasta la fecha. IT07 - AUDITORIA INTERNA .docx",
    "position": 82
  },
  {
    "id": "seed-tracker-row-86",
    "sourceKey": "sheet-row-86",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-30",
    "title": "Generación Instructivo operacional Revisión",
    "taskType": "Entrenamiento",
    "description": "Definición y estandarización de proceso de revisión",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-30",
    "response": "Todavía no se vió el punto",
    "position": 83
  },
  {
    "id": "seed-tracker-row-87",
    "sourceKey": "sheet-row-87",
    "process": "AUDITORIAS",
    "taskDate": "2026-08-06",
    "title": "Generación de UBICACIÓN NO DISPONIBLE para Revisión",
    "taskType": "Funcion SGL",
    "description": "Durante el proceso de preparación la gente de picking en caso de encontrar articulos para revision debe hacer transferencia de caja a una UBICACIÓN no diponible para la gente de REVISION",
    "priority": 3,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-08-06",
    "response": "No cuento con permiso para crear ubicaciones. Vamos a esperar a acercarse a fecha de lanzamiento",
    "position": 84
  },
  {
    "id": "seed-tracker-row-88",
    "sourceKey": "sheet-row-88",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Operadores",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento operacional para realizar los procedimientos y busqueda desde sistema",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-28",
    "response": "A la espera de definición de Instructivo",
    "position": 85
  },
  {
    "id": "seed-tracker-row-89",
    "sourceKey": "sheet-row-89",
    "process": "AUDITORIAS",
    "taskDate": "2026-07-24",
    "title": "Entrenamiento de Jefe de sector",
    "taskType": "Entrenamiento",
    "description": "Entrenamiento a jefe de auditoría. Busqueda de historico de movimientos y articulos, bajada de stock, stock por articulo y avance de controles",
    "priority": 2,
    "responsible": "Logistica",
    "status": "No Realizado",
    "isDoing": false,
    "isCompleted": false,
    "isDone": false,
    "isVerified": false,
    "responseDate": "2026-07-28",
    "response": "A la espera de definición de Instructivo",
    "position": 86
  }
];

