/*******************************************************
 * SII V2 - CONFIGURACIÓN GENERAL
 * Versión 0.1.001
 *******************************************************/

const SII_VERSION = '0.1.001';

const SII_CFG = {
  SHEETS: {
    PARAMETROS: 'PARAMETROS',
    ORDENES: 'ORDENES',
    DETALLE: 'DETALLE_IMPORTACIONES',
    EMBARQUES: 'EMBARQUES',
    PAGOS: 'PAGOS',
    HISTORIAL: 'HISTORIAL',
    CONTROL_MIGRACION: 'CONTROL_MIGRACION',
    DASHBOARD: 'DASHBOARD',

    PROVEEDORES: 'PROVEEDORES',
    MARCAS: 'MARCAS',
    PRODUCTOS: 'PRODUCTOS',
    EQUIVALENCIAS_SKU: 'EQUIVALENCIAS_SKU',
    PENDIENTES_SKU: 'PENDIENTES_SKU',

    STOCK: 'STOCK',
    SKU_STOCK_NO_ENCONTRADOS: 'SKU_STOCK_NO_ENCONTRADOS',
    LOG_IMPORTACIONES: 'LOG_IMPORTACIONES',

    DETALLE_RECIBIDOS: 'DETALLE_RECIBIDOS',

    RECEPCIONES: 'RECEPCIONES',
    EVENTOS_IMPORTACION: 'EVENTOS_IMPORTACION',

    VENTAS: 'VENTAS',
    DOCUMENTOS: 'DOCUMENTOS',
    INDICADORES: 'INDICADORES',
    PLAN_COMPRAS: 'PLAN_COMPRAS'
  },

  ESTADOS_CERRADOS: [
    'INGRESADO',
    'CERRADO'
  ],

  ESTADOS_IMPORTACION: [
    'PENDIENTE',
    'EN FABRICA',
    'A EMBARCAR',
    'EMBARCADO',
    'A INGRESAR',
    'INGRESADO',
    'CERRADO'
  ],

  COLOR_ENCABEZADO: '#1F4E78',
  COLOR_TEXTO_ENCABEZADO: '#FFFFFF'
};
