begin;

-- Todo el contenido del portal vive en un esquema independiente.
create schema if not exists portal_aftermarket;

-- El navegador no accede directamente a estas tablas. Las operaciones se
-- realizarán desde el servidor de Next.js después de validar Google OAuth.
revoke all on schema portal_aftermarket from public, anon, authenticated;
grant usage on schema portal_aftermarket to service_role;

create table if not exists portal_aftermarket.wms_modules (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  icon_key text not null default 'folder',
  position integer not null default 0 check (position >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists portal_aftermarket.wms_resources (
  id bigint generated by default as identity primary key,
  module_id bigint not null references portal_aftermarket.wms_modules(id) on delete restrict,
  slug text not null,
  name text not null,
  url text not null check (url ~ '^https?://'),
  resource_type text not null check (resource_type in ('Carpeta', 'Documento', 'Presentación', 'Planilla')),
  is_primary boolean not null default false,
  position integer not null default 0 check (position >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (module_id, slug)
);

create index if not exists wms_modules_active_position_idx
  on portal_aftermarket.wms_modules (is_active, position);

create index if not exists wms_resources_module_active_position_idx
  on portal_aftermarket.wms_resources (module_id, is_active, position);

create unique index if not exists wms_resources_one_active_primary_idx
  on portal_aftermarket.wms_resources (module_id)
  where is_primary and is_active;

alter table portal_aftermarket.wms_modules enable row level security;
alter table portal_aftermarket.wms_resources enable row level security;

revoke all on portal_aftermarket.wms_modules from public, anon, authenticated;
revoke all on portal_aftermarket.wms_resources from public, anon, authenticated;
grant select, insert, update, delete on portal_aftermarket.wms_modules to service_role;
grant select, insert, update, delete on portal_aftermarket.wms_resources to service_role;
grant usage, select on all sequences in schema portal_aftermarket to service_role;

alter default privileges in schema portal_aftermarket revoke all on tables from public, anon, authenticated;
alter default privileges in schema portal_aftermarket revoke all on sequences from public, anon, authenticated;
alter default privileges in schema portal_aftermarket grant select, insert, update, delete on tables to service_role;
alter default privileges in schema portal_aftermarket grant usage, select on sequences to service_role;

-- Datos iniciales. ON CONFLICT DO NOTHING garantiza que una nueva ejecución
-- no reemplace modificaciones futuras realizadas desde el portal.
insert into portal_aftermarket.wms_modules (slug, name, description, icon_key, position)
values
  ('capacitacion', 'Plan de capacitación', 'Materiales de formación, configuraciones y documentación compartida con el equipo SGL.', 'graduation-cap', 0),
  ('funcionalidades', 'Funcionalidades', 'Manuales, glosarios y herramientas para comprender la operación del sistema.', 'boxes', 1),
  ('lanzamiento', 'Lanzamiento', 'Presentación general y seguimiento del estado de lanzamiento de SGLWMS.', 'rocket', 2),
  ('operaciones', 'Operaciones logísticas', 'Procedimientos y recursos para recepción, inventario y control de la operación.', 'warehouse', 3),
  ('proyecto', 'Proyecto SGL', 'Documentación de referencia y presentación general del proyecto Distrimar - SGLWMS.', 'folder-kanban', 4),
  ('manuales', 'Manuales de usuario', 'Documentación funcional destinada a los usuarios de la operación WMS.', 'book-open', 5),
  ('otros', 'Otros documentos', 'Carpeta complementaria para documentación adicional relacionada con la implementación.', 'files', 6)
on conflict (slug) do nothing;

insert into portal_aftermarket.wms_resources
  (module_id, slug, name, url, resource_type, is_primary, position)
select m.id, v.slug, v.name, v.url, v.resource_type, v.is_primary, v.position
from portal_aftermarket.wms_modules m
join (values
  ('capacitacion', 'principal', 'Plan de capacitación - SGL', 'https://drive.google.com/drive/folders/0AN0BEGxurtnnUk9PVA', 'Carpeta', true, 0),
  ('capacitacion', 'instructivos-operacionales', 'Instructivos Operacionales', 'https://drive.google.com/drive/folders/12AZsSW4OLbl9J6TlaS2ptlfRgumnwW5u?usp=drive_link', 'Carpeta', false, 1),
  ('capacitacion', 'configuraciones-wms', 'Configuraciones WMS', 'https://drive.google.com/drive/folders/1DlpjKy6q-pdh45MTeA7jxzdybMNHnFoV?usp=drive_link', 'Carpeta', false, 2),
  ('capacitacion', 'entrenamiento-equipo-sgl', 'Entrenamiento - Equipo SGL', 'https://drive.google.com/drive/folders/1rEpt1z4K3Zp8XzrENxQBzhw6S_ZGiS5?usp=drive_link', 'Carpeta', false, 3),
  ('capacitacion', 'documentos-equipo-sgl', 'Documentos - Equipo SGL', 'https://drive.google.com/drive/folders/1IeNIePurdDI-u6C4oL2xdw3LN5luj1EN?usp=drive_link', 'Carpeta', false, 4),

  ('funcionalidades', 'principal', 'Funcionalidades', 'https://drive.google.com/drive/folders/0AJj9qkDUVP7gUk9PVA', 'Carpeta', true, 0),
  ('funcionalidades', 'manual-sglwms', 'Manual SGLWMS', 'https://drive.google.com/drive/folders/1tmT3Y9TZLjDgifVtkh6IPJ-DYZxlASru', 'Carpeta', false, 1),
  ('funcionalidades', 'glosario-interfaz', 'Glosario - Interfaz', 'https://docs.google.com/document/d/1mKFLsX7eeNadSaftiVbvVo1CZfKj3_LL/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Documento', false, 2),
  ('funcionalidades', 'glosario-rf', 'Glosario - RF', 'https://docs.google.com/document/d/1gIpES2AiaZeappub4cgWlug2qfRfM58e/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Documento', false, 3),
  ('funcionalidades', 'herramientas-gestion', 'Herramientas de Gestión', 'https://docs.google.com/document/d/10sc2NiStP6KvK7u3H9TKqpDe6qX8Uvuv/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Documento', false, 4),

  ('lanzamiento', 'principal', 'Lanzamiento', 'https://docs.google.com/presentation/d/13YmInCLNNC8pvwDa3c4TzBDaKagncGzo/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Presentación', true, 0),
  ('lanzamiento', 'estado-lanzamiento', 'Estado - Lanzamiento SGLWMS', 'https://docs.google.com/spreadsheets/d/11kedQyHUKaHY6uwFxwbahPvm_CuxniDgHJiXk3makCs/edit?usp=sharing', 'Planilla', false, 1),

  ('operaciones', 'principal', 'Operaciones logísticas', 'https://drive.google.com/drive/folders/1tmT3Y9TZLjDgifVtkh6IPJ-DYZxlASru', 'Carpeta', true, 0),
  ('operaciones', 'procedimiento-reportes', 'Procedimiento y Reportes', 'https://drive.google.com/drive/folders/13BB37j8FC79jOltCyTVsWDxURJ-zQuHy', 'Carpeta', false, 1),
  ('operaciones', 'recepcion', 'Recepción', 'https://drive.google.com/drive/folders/1dPCKar02VQ3vbe2Ye7XXpTr1a876LfNB?usp=drive_link', 'Carpeta', false, 2),
  ('operaciones', 'inventario', 'Inventario', 'https://drive.google.com/drive/folders/19oJbzr6U8g9gGEpgEiSHMTkHbgPtZYSp', 'Carpeta', false, 3),
  ('operaciones', 'auditorias-internas', 'Auditorías Internas', 'https://drive.google.com/drive/folders/1SGPqpKlhdByg1l7GVFBh5psTnLYWFU_W', 'Carpeta', false, 4),
  ('operaciones', 'procedimiento-meli', 'Procedimiento MELI', 'https://docs.google.com/document/d/1nvyiJHjwrQ6loKj5aevjPVHiEA244ME8/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Documento', false, 5),

  ('proyecto', 'principal', 'Proyecto SGL', 'https://drive.google.com/drive/folders/1xYNPfw0xtsna7WXZOhOHF4ZQNe_VpMVp?usp=drive_link', 'Carpeta', true, 0),
  ('proyecto', 'proyecto-distrimar-sglwms', 'Proyecto DISTRIMAR - SGLWMS', 'https://docs.google.com/presentation/d/13YmInCLNNC8pvwDa3c4TzBDaKagncGzo/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Presentación', false, 1),

  ('manuales', 'principal', 'Manuales de usuario', 'https://drive.google.com/drive/folders/1w6Ra2wC73wNGLWlqCp8KtveTLM9NEoIP?usp=drive_link', 'Carpeta', true, 0),
  ('manuales', 'requerimientos-funcionales', 'Requerimientos funcionales', 'https://docs.google.com/document/d/1jMxaOHj__9S2pqxvCNSnBfIYrIXsEDlT/edit?usp=sharing&ouid=101674496346329341048&rtpof=true&sd=true', 'Documento', false, 1),

  ('otros', 'principal', 'Otros documentos', 'https://drive.google.com/drive/folders/1HRpP0o1cs1WuXoW0Se1Tq2Yqhi37Ndf4?usp=drive_link', 'Carpeta', true, 0)
) as v(module_slug, slug, name, url, resource_type, is_primary, position)
  on m.slug = v.module_slug
on conflict (module_id, slug) do nothing;

commit;
