begin;

-- Fase 2.0 / Compras
-- Base transaccional para importar snapshots de stock desde los sistemas origen.
-- WMS -> WARNES
-- OCTOSIS -> ESCOBAR
--
-- Esta migración NO depende de Google Sheets y no crea todavía el maestro de productos.
-- Cada archivo importado queda registrado como una ejecución independiente para conservar
-- trazabilidad e histórico.

create table if not exists portal_aftermarket.compras_stock_imports (
  id bigint generated by default as identity primary key,

  source_system text not null
    check (source_system in ('WMS', 'OCTOSIS')),

  deposito text not null
    check (deposito in ('WARNES', 'ESCOBAR')),

  archivo_origen text not null
    check (btrim(archivo_origen) <> ''),

  -- SHA-256 del archivo original. Permite evitar procesar dos veces exactamente
  -- el mismo archivo para el mismo sistema y depósito.
  archivo_sha256 text,

  -- Fecha propia del archivo si en el futuro podemos obtenerla desde la fuente.
  -- No es obligatoria porque algunos XLS exportados no la informan de forma confiable.
  fecha_archivo timestamptz,

  fecha_importacion timestamptz not null default now(),

  estado text not null default 'PROCESANDO'
    check (estado in ('PROCESANDO', 'VALIDADO', 'ERROR', 'DESCARTADO')),

  filas_origen integer not null default 0
    check (filas_origen >= 0),

  filas_validas integer not null default 0
    check (filas_validas >= 0),

  filas_rechazadas integer not null default 0
    check (filas_rechazadas >= 0),

  error_message text,

  -- Información técnica opcional del importador:
  -- nombre de hoja, encabezado detectado, versión del parser, etc.
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists portal_aftermarket.compras_stock_import_items (
  id bigint generated by default as identity primary key,

  import_id bigint not null
    references portal_aftermarket.compras_stock_imports(id)
    on delete cascade,

  -- El importador debe guardar aquí el SKU ya limpio/normalizado.
  sku text not null
    check (btrim(sku) <> ''),

  -- Numeric permite conservar cantidades decimales si alguna fuente las utiliza
  -- en el futuro. No restringimos a >= 0 para no ocultar posibles inconsistencias
  -- provenientes del sistema origen.
  stock numeric(18,3) not null,

  -- Fila original del Excel para trazabilidad y diagnóstico.
  source_row_number integer
    check (source_row_number is null or source_row_number > 0),

  created_at timestamptz not null default now(),

  unique (import_id, sku)
);

create table if not exists portal_aftermarket.compras_stock_import_errors (
  id bigint generated by default as identity primary key,

  import_id bigint not null
    references portal_aftermarket.compras_stock_imports(id)
    on delete cascade,

  source_row_number integer
    check (source_row_number is null or source_row_number > 0),

  sku_raw text,
  error_code text not null default 'INVALID_ROW',
  error_message text not null,

  -- Conserva la fila problemática sin obligarnos a modelar todas las columnas
  -- específicas de WMS u Octosis.
  raw_data jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

-- No permitir importar dos veces exactamente el mismo archivo para la misma fuente.
create unique index if not exists compras_stock_imports_file_hash_uidx
  on portal_aftermarket.compras_stock_imports (
    source_system,
    deposito,
    archivo_sha256
  )
  where archivo_sha256 is not null;

create index if not exists compras_stock_imports_deposito_fecha_idx
  on portal_aftermarket.compras_stock_imports (
    deposito,
    fecha_importacion desc,
    id desc
  );

create index if not exists compras_stock_imports_estado_idx
  on portal_aftermarket.compras_stock_imports (estado);

create index if not exists compras_stock_import_items_import_idx
  on portal_aftermarket.compras_stock_import_items (import_id);

create index if not exists compras_stock_import_items_sku_idx
  on portal_aftermarket.compras_stock_import_items (sku);

create index if not exists compras_stock_import_errors_import_idx
  on portal_aftermarket.compras_stock_import_errors (import_id);

-- Snapshot vigente por depósito.
-- Sólo utiliza la última importación VALIDADA de WARNES y la última de ESCOBAR.
create or replace view portal_aftermarket.compras_stock_actual as
with latest_imports as (
  select distinct on (deposito)
    id,
    source_system,
    deposito,
    archivo_origen,
    fecha_archivo,
    fecha_importacion
  from portal_aftermarket.compras_stock_imports
  where estado = 'VALIDADO'
  order by deposito, fecha_importacion desc, id desc
)
select
  i.sku,
  li.deposito,
  i.stock,
  li.source_system,
  li.id as import_id,
  li.archivo_origen,
  li.fecha_archivo,
  li.fecha_importacion
from latest_imports li
join portal_aftermarket.compras_stock_import_items i
  on i.import_id = li.id;

-- Vista práctica para el Dashboard y para el resto de Compras:
-- una fila por SKU con ambos depósitos.
create or replace view portal_aftermarket.compras_stock_actual_por_sku as
select
  sku,

  coalesce(
    max(stock) filter (where deposito = 'WARNES'),
    0::numeric
  )::numeric(18,3) as stock_warnes,

  coalesce(
    max(stock) filter (where deposito = 'ESCOBAR'),
    0::numeric
  )::numeric(18,3) as stock_escobar,

  (
    coalesce(max(stock) filter (where deposito = 'WARNES'), 0::numeric)
    +
    coalesce(max(stock) filter (where deposito = 'ESCOBAR'), 0::numeric)
  )::numeric(18,3) as stock_total,

  max(fecha_importacion) filter (where deposito = 'WARNES')
    as fecha_stock_warnes,

  max(fecha_importacion) filter (where deposito = 'ESCOBAR')
    as fecha_stock_escobar,

  max(import_id) filter (where deposito = 'WARNES')
    as import_id_warnes,

  max(import_id) filter (where deposito = 'ESCOBAR')
    as import_id_escobar

from portal_aftermarket.compras_stock_actual
group by sku;

-- Seguridad: igual que el resto de portal_aftermarket.
-- El navegador no accede directamente a estas tablas.
alter table portal_aftermarket.compras_stock_imports enable row level security;
alter table portal_aftermarket.compras_stock_import_items enable row level security;
alter table portal_aftermarket.compras_stock_import_errors enable row level security;

revoke all on portal_aftermarket.compras_stock_imports
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_stock_import_items
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_stock_import_errors
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_stock_actual
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_stock_actual_por_sku
  from public, anon, authenticated;

-- La aplicación Next.js opera exclusivamente mediante la service role.
grant select, insert, update
  on portal_aftermarket.compras_stock_imports
  to service_role;

grant select, insert, update, delete
  on portal_aftermarket.compras_stock_import_items
  to service_role;

grant select, insert, update, delete
  on portal_aftermarket.compras_stock_import_errors
  to service_role;

grant select
  on portal_aftermarket.compras_stock_actual
  to service_role;

grant select
  on portal_aftermarket.compras_stock_actual_por_sku
  to service_role;

grant usage, select
  on all sequences in schema portal_aftermarket
  to service_role;

commit;
