begin;

create table if not exists portal_aftermarket.compras_sync_requests (
  id bigint generated by default as identity primary key,

  sync_type text not null
    check (sync_type in ('STOCK_WARNES')),

  status text not null default 'PENDIENTE'
    check (status in ('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'ERROR')),

  requested_by text not null
    check (btrim(requested_by) <> ''),

  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,

  github_run_id bigint,
  import_id bigint
    references portal_aftermarket.compras_stock_imports(id)
    on delete set null,

  error_message text,
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists compras_sync_requests_status_idx
  on portal_aftermarket.compras_sync_requests (status, requested_at desc);

create index if not exists compras_sync_requests_type_idx
  on portal_aftermarket.compras_sync_requests (sync_type, requested_at desc);

alter table portal_aftermarket.compras_sync_requests enable row level security;

revoke all on portal_aftermarket.compras_sync_requests
  from public, anon, authenticated;

grant select, insert, update
  on portal_aftermarket.compras_sync_requests
  to service_role;

grant usage, select
  on all sequences in schema portal_aftermarket
  to service_role;

commit;
