begin;

-- Hito 1 / Compras - Ventas
-- Snapshots auditables e independientes de las tablas de stock.

create table if not exists portal_aftermarket.compras_ventas_imports (
  id bigint generated by default as identity primary key,

  source_system text not null
    check (source_system in ('SQL_SERVER')),

  source_name text not null
    check (btrim(source_name) <> ''),

  query_version text not null
    check (btrim(query_version) <> ''),

  dataset_sha256 text not null
    check (dataset_sha256 ~ '^[0-9a-f]{64}$'),

  period_from date not null,
  period_to date not null,
  source_max_date date,
  fecha_importacion timestamptz not null default now(),

  estado text not null default 'PROCESANDO'
    check (estado in ('PROCESANDO', 'VALIDADO', 'ERROR', 'DESCARTADO')),

  filas_origen bigint not null default 0
    check (filas_origen >= 0),

  filas_validas integer not null default 0
    check (filas_validas >= 0),

  filas_rechazadas bigint not null default 0
    check (filas_rechazadas >= 0),

  sku_count integer not null default 0
    check (sku_count >= 0),

  codigo_count integer not null default 0
    check (codigo_count >= 0),

  period_count integer not null default 0
    check (period_count >= 0),

  total_unidades_netas numeric(24,3) not null default 0,
  total_facturado_neto_sin_iva numeric(24,4) not null default 0,
  error_message text,
  warnings jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (period_to >= period_from),
  unique (source_system, dataset_sha256)
);

create table if not exists portal_aftermarket.compras_ventas_import_items (
  id bigint generated by default as identity primary key,
  import_id bigint not null
    references portal_aftermarket.compras_ventas_imports(id)
    on delete cascade,

  codigo text not null
    check (btrim(codigo) <> ''),

  sku text not null
    check (btrim(sku) <> ''),

  -- Clave de cruce equivalente a vmNormalizarClaveSku_ del legacy.
  sku_key text not null
    check (btrim(sku_key) <> ''),

  descripcion text,

  empresa text not null
    check (empresa in ('DTM', 'IMP', 'JNM', 'NLI', 'NLD')),

  periodo date not null
    check (periodo = date_trunc('month', periodo)::date),

  unidades_netas numeric(24,3) not null,
  facturado_neto_sin_iva numeric(24,4) not null,

  source_rows bigint not null default 0
    check (source_rows >= 0),

  created_at timestamptz not null default now(),

  unique (import_id, codigo, empresa, periodo)
);

create table if not exists portal_aftermarket.compras_ventas_import_errors (
  id bigint generated by default as identity primary key,
  import_id bigint not null
    references portal_aftermarket.compras_ventas_imports(id)
    on delete cascade,

  codigo_raw text,
  sku_raw text,
  error_code text not null default 'INVALID_ROW',
  error_message text not null,
  affected_rows bigint not null default 0
    check (affected_rows >= 0),
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists compras_ventas_imports_fecha_idx
  on portal_aftermarket.compras_ventas_imports (
    fecha_importacion desc,
    id desc
  );

create index if not exists compras_ventas_imports_estado_idx
  on portal_aftermarket.compras_ventas_imports (estado);

create index if not exists compras_ventas_items_import_idx
  on portal_aftermarket.compras_ventas_import_items (import_id);

create index if not exists compras_ventas_items_sku_periodo_idx
  on portal_aftermarket.compras_ventas_import_items (sku, periodo);

create index if not exists compras_ventas_items_sku_key_periodo_idx
  on portal_aftermarket.compras_ventas_import_items (sku_key, periodo);

create index if not exists compras_ventas_errors_import_idx
  on portal_aftermarket.compras_ventas_import_errors (import_id);

create or replace view portal_aftermarket.compras_ventas_actual_import as
select
  id as import_id,
  source_system,
  source_name,
  query_version,
  period_from,
  period_to,
  source_max_date,
  fecha_importacion,
  filas_origen,
  filas_validas,
  filas_rechazadas,
  sku_count,
  codigo_count,
  period_count,
  total_unidades_netas,
  total_facturado_neto_sin_iva,
  warnings,
  metadata
from portal_aftermarket.compras_ventas_imports
where estado = 'VALIDADO'
order by fecha_importacion desc, id desc
limit 1;

create or replace view portal_aftermarket.compras_ventas_actual_mensual as
select
  i.sku,
  i.sku_key,
  i.codigo,
  i.descripcion,
  i.empresa,
  i.periodo,
  i.unidades_netas,
  i.facturado_neto_sin_iva,
  i.source_rows,
  a.import_id,
  a.fecha_importacion,
  a.source_max_date
from portal_aftermarket.compras_ventas_actual_import a
join portal_aftermarket.compras_ventas_import_items i
  on i.import_id = a.import_id;

create or replace view portal_aftermarket.compras_ventas_actual_por_sku as
select
  sku_key,
  max(sku) as sku,
  periodo,
  sum(unidades_netas)::numeric(24,3) as unidades_netas,
  sum(facturado_neto_sin_iva)::numeric(24,4) as facturado_neto_sin_iva,
  max(import_id) as import_id,
  max(fecha_importacion) as fecha_importacion,
  max(source_max_date) as source_max_date
from portal_aftermarket.compras_ventas_actual_mensual
group by sku_key, periodo;

-- Se conserva import_id como FK exclusiva del snapshot de stock WARNES.
-- Ventas utiliza una FK separada para no alterar el contrato productivo actual.
alter table portal_aftermarket.compras_sync_requests
  add column if not exists ventas_import_id bigint
    references portal_aftermarket.compras_ventas_imports(id)
    on delete set null;

alter table portal_aftermarket.compras_sync_requests
  drop constraint if exists compras_sync_requests_sync_type_check;

alter table portal_aftermarket.compras_sync_requests
  add constraint compras_sync_requests_sync_type_check
    check (sync_type in ('STOCK_WARNES', 'VENTAS'));

create index if not exists compras_sync_requests_ventas_import_idx
  on portal_aftermarket.compras_sync_requests (ventas_import_id);

create unique index if not exists compras_sync_requests_ventas_active_uidx
  on portal_aftermarket.compras_sync_requests (sync_type)
  where sync_type = 'VENTAS'
    and status in ('PENDIENTE', 'PROCESANDO');

alter table portal_aftermarket.compras_ventas_imports enable row level security;
alter table portal_aftermarket.compras_ventas_import_items enable row level security;
alter table portal_aftermarket.compras_ventas_import_errors enable row level security;

revoke all on portal_aftermarket.compras_ventas_imports
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_ventas_import_items
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_ventas_import_errors
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_ventas_actual_import
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_ventas_actual_mensual
  from public, anon, authenticated;

revoke all on portal_aftermarket.compras_ventas_actual_por_sku
  from public, anon, authenticated;

grant select, insert, update
  on portal_aftermarket.compras_ventas_imports
  to service_role;

grant select, insert
  on portal_aftermarket.compras_ventas_import_items
  to service_role;

grant select, insert
  on portal_aftermarket.compras_ventas_import_errors
  to service_role;

grant select
  on portal_aftermarket.compras_ventas_actual_import
  to service_role;

grant select
  on portal_aftermarket.compras_ventas_actual_mensual
  to service_role;

grant select
  on portal_aftermarket.compras_ventas_actual_por_sku
  to service_role;

grant usage, select
  on all sequences in schema portal_aftermarket
  to service_role;

commit;
