begin;

create table if not exists portal_aftermarket.compras_ordenes_imports (
  id bigint generated by default as identity primary key,
  source_file_id text not null,
  source_name text not null,
  source_modified_at timestamptz,
  dataset_sha256 text not null unique check (dataset_sha256 ~ '^[0-9a-f]{64}$'),
  estado text not null default 'PROCESANDO' check (estado in ('PROCESANDO','VALIDADO','ERROR')),
  fecha_importacion timestamptz not null default now(),
  filas_origen integer not null,
  filas_validas integer not null,
  filas_rechazadas integer not null,
  ordenes_count integer not null,
  total_unidades numeric(24,3) not null,
  status_counts jsonb not null default '{}'::jsonb,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists portal_aftermarket.compras_ordenes_import_items (
  import_id bigint not null references portal_aftermarket.compras_ordenes_imports(id) on delete cascade,
  fila_origen integer not null,
  orden text not null,
  marca text,
  item text not null,
  cantidad numeric(24,3) not null,
  status text not null,
  situacion text,
  packing_list text,
  prueba text,
  precio numeric(24,4),
  precio_original text,
  moneda text,
  fecha date,
  proveedor text,
  fecha_deposito text,
  fecha_entrega text,
  primary key (import_id, fila_origen)
);

create index if not exists compras_ordenes_items_order_idx on portal_aftermarket.compras_ordenes_import_items (orden);
create index if not exists compras_ordenes_items_item_idx on portal_aftermarket.compras_ordenes_import_items (item);

create or replace view portal_aftermarket.compras_ordenes_actual_import as
select * from portal_aftermarket.compras_ordenes_imports
where estado = 'VALIDADO'
order by fecha_importacion desc, id desc limit 1;

alter table portal_aftermarket.compras_sync_requests add column if not exists ordenes_import_id bigint
  references portal_aftermarket.compras_ordenes_imports(id) on delete set null;
alter table portal_aftermarket.compras_sync_requests drop constraint if exists compras_sync_requests_sync_type_check;
alter table portal_aftermarket.compras_sync_requests add constraint compras_sync_requests_sync_type_check
  check (sync_type in ('STOCK_WARNES','VENTAS','ORDENES'));
create unique index if not exists compras_sync_requests_ordenes_active_uidx
  on portal_aftermarket.compras_sync_requests (sync_type)
  where sync_type = 'ORDENES' and status in ('PENDIENTE','PROCESANDO');

alter table portal_aftermarket.compras_ordenes_imports enable row level security;
alter table portal_aftermarket.compras_ordenes_import_items enable row level security;
revoke all on portal_aftermarket.compras_ordenes_imports from public, anon, authenticated;
revoke all on portal_aftermarket.compras_ordenes_import_items from public, anon, authenticated;
revoke all on portal_aftermarket.compras_ordenes_actual_import from public, anon, authenticated;
grant select, insert, update on portal_aftermarket.compras_ordenes_imports to service_role;
grant select, insert on portal_aftermarket.compras_ordenes_import_items to service_role;
grant select on portal_aftermarket.compras_ordenes_actual_import to service_role;
grant usage, select on all sequences in schema portal_aftermarket to service_role;

commit;
