begin;

-- Copia auditable y de sólo lectura del Sheet legacy. Cada pestaña se publica
-- por separado: una importación incompleta nunca reemplaza el snapshot vigente.
create table if not exists portal_aftermarket.compras_sheet_imports (
  id bigint generated by default as identity primary key,
  spreadsheet_id text not null check (btrim(spreadsheet_id) <> ''),
  sheet_name text not null check (btrim(sheet_name) <> ''),
  dataset_sha256 text not null check (dataset_sha256 ~ '^[0-9a-f]{64}$'),
  estado text not null default 'PROCESANDO'
    check (estado in ('PROCESANDO', 'VALIDADO', 'ERROR')),
  row_count integer not null check (row_count >= 0),
  time_zone text not null,
  fecha_importacion timestamptz not null default now(),
  ultima_revision timestamptz not null default now(),
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists portal_aftermarket.compras_sheet_import_rows (
  import_id bigint not null references portal_aftermarket.compras_sheet_imports(id) on delete cascade,
  row_index integer not null check (row_index >= 0),
  row_values jsonb not null check (jsonb_typeof(row_values) = 'array'),
  primary key (import_id, row_index)
);

-- El lote publica todas las pestañas del Dashboard en una sola transición.
-- Las importaciones por hoja pueden reutilizarse si el contenido no cambió.
create table if not exists portal_aftermarket.compras_sheet_batches (
  id bigint generated by default as identity primary key,
  spreadsheet_id text not null check (btrim(spreadsheet_id) <> ''),
  estado text not null default 'PROCESANDO'
    check (estado in ('PROCESANDO', 'VALIDADO', 'ERROR')),
  sheet_count integer not null check (sheet_count > 0),
  fecha_importacion timestamptz not null default now(),
  error_message text
);

create table if not exists portal_aftermarket.compras_sheet_batch_items (
  batch_id bigint not null references portal_aftermarket.compras_sheet_batches(id) on delete cascade,
  sheet_name text not null,
  import_id bigint not null references portal_aftermarket.compras_sheet_imports(id),
  primary key (batch_id, sheet_name)
);

create unique index if not exists compras_sheet_imports_valid_hash_uidx
  on portal_aftermarket.compras_sheet_imports (spreadsheet_id, sheet_name, dataset_sha256)
  where estado = 'VALIDADO';

create index if not exists compras_sheet_imports_current_idx
  on portal_aftermarket.compras_sheet_imports
  (spreadsheet_id, sheet_name, ultima_revision desc, id desc)
  where estado = 'VALIDADO';

create or replace view portal_aftermarket.compras_sheet_actual_import as
select
  b.id as batch_id,
  i.id as import_id,
  i.spreadsheet_id,
  i.sheet_name,
  i.dataset_sha256,
  i.row_count,
  i.time_zone,
  i.fecha_importacion,
  b.fecha_importacion as fecha_lote
from (
  select distinct on (b.spreadsheet_id) b.id, b.spreadsheet_id, b.fecha_importacion
  from portal_aftermarket.compras_sheet_batches
    b
  where b.estado = 'VALIDADO'
    and b.sheet_count = (
      select count(*) from portal_aftermarket.compras_sheet_batch_items bi
      join portal_aftermarket.compras_sheet_imports i on i.id = bi.import_id
      where bi.batch_id = b.id and i.estado = 'VALIDADO'
    )
  order by b.spreadsheet_id, b.id desc
) b
join portal_aftermarket.compras_sheet_batch_items bi on bi.batch_id = b.id
join portal_aftermarket.compras_sheet_imports i on i.id = bi.import_id;

alter table portal_aftermarket.compras_sheet_imports enable row level security;
alter table portal_aftermarket.compras_sheet_import_rows enable row level security;
alter table portal_aftermarket.compras_sheet_batches enable row level security;
alter table portal_aftermarket.compras_sheet_batch_items enable row level security;
revoke all on portal_aftermarket.compras_sheet_imports from public, anon, authenticated;
revoke all on portal_aftermarket.compras_sheet_import_rows from public, anon, authenticated;
revoke all on portal_aftermarket.compras_sheet_batches from public, anon, authenticated;
revoke all on portal_aftermarket.compras_sheet_batch_items from public, anon, authenticated;
revoke all on portal_aftermarket.compras_sheet_actual_import from public, anon, authenticated;
grant select, insert, update on portal_aftermarket.compras_sheet_imports to service_role;
grant select, insert on portal_aftermarket.compras_sheet_import_rows to service_role;
grant select, insert, update on portal_aftermarket.compras_sheet_batches to service_role;
grant select, insert on portal_aftermarket.compras_sheet_batch_items to service_role;
grant select on portal_aftermarket.compras_sheet_actual_import to service_role;
grant usage, select on all sequences in schema portal_aftermarket to service_role;

commit;
