begin;

-- Una sola fuente de verdad para decisiones; las hojas quedan como insumo de lectura.
create table if not exists portal_aftermarket.compras_gestion_decisiones (
  sku text primary key check (sku = upper(btrim(sku)) and sku <> ''),
  estado_gestion text check (estado_gestion in
    ('PENDIENTE', 'COTIZAR', 'APROBADO', 'NO COMPRAR', 'POSTERGAR', 'ENVIADO A COMPRA')),
  cantidad_decidida numeric(18, 2) not null default 0 check (cantidad_decidida >= 0),
  observacion text not null default '' check (char_length(observacion) <= 1000),
  responsable text not null default '',
  fecha_decision timestamptz,
  requiere_revision boolean not null default false,
  version integer not null default 1 check (version > 0),
  lote_origen bigint references portal_aftermarket.compras_sheet_batches(id),
  actualizado_en timestamptz not null default now(),
  constraint compras_gestion_revision_estado_chk check
    ((requiere_revision and estado_gestion is null) or (not requiere_revision and estado_gestion is not null))
);

create table if not exists portal_aftermarket.compras_gestion_eventos (
  id bigint generated by default as identity primary key,
  sku text not null references portal_aftermarket.compras_gestion_decisiones(sku),
  version integer not null,
  tipo text not null check (tipo in ('MIGRACION', 'DECISION')),
  estado_gestion text,
  cantidad_decidida numeric(18, 2) not null,
  observacion text not null,
  actor text not null,
  fecha_evento timestamptz not null default now(),
  unique (sku, version)
);

create index if not exists compras_gestion_eventos_sku_fecha_idx
  on portal_aftermarket.compras_gestion_eventos (sku, fecha_evento desc);

-- Importación inicial de un lote conciliado. No puede reemplazar decisiones ya migradas.
create or replace function portal_aftermarket.compras_gestion_importar(
  p_registros jsonb, p_lote_origen bigint
) returns integer language plpgsql set search_path = '' as $$
declare
  v_total integer;
begin
  if jsonb_typeof(p_registros) <> 'array' then raise exception 'Importación inválida'; end if;
  v_total := jsonb_array_length(p_registros);
  if v_total < 3000 or v_total > 100000 then raise exception 'Cantidad de SKU inesperada: %', v_total; end if;
  if not exists (select 1 from portal_aftermarket.compras_sheet_batches where id = p_lote_origen and estado = 'VALIDADO') then
    raise exception 'El lote de origen no está validado';
  end if;
  if exists (select 1 from portal_aftermarket.compras_gestion_decisiones) then
    raise exception 'Gestión ya fue importada; no se sobrescribirán decisiones';
  end if;

  insert into portal_aftermarket.compras_gestion_decisiones
    (sku, estado_gestion, cantidad_decidida, observacion, responsable, fecha_decision, requiere_revision, lote_origen)
  select upper(btrim(x.sku)),
    case when x.requiere_revision then null else x.estado_gestion end,
    x.cantidad_decidida, x.observacion, x.responsable, x.fecha_decision,
    x.requiere_revision, p_lote_origen
  from jsonb_to_recordset(p_registros) as x(
    sku text, estado_gestion text, cantidad_decidida numeric,
    observacion text, responsable text, fecha_decision timestamptz,
    requiere_revision boolean
  );
  if (select count(*) from portal_aftermarket.compras_gestion_decisiones) <> v_total then
    raise exception 'La importación no contiene exactamente % SKU', v_total;
  end if;
  insert into portal_aftermarket.compras_gestion_eventos
    (sku, version, tipo, estado_gestion, cantidad_decidida, observacion, actor, fecha_evento)
  select sku, version, 'MIGRACION', estado_gestion, cantidad_decidida, observacion,
    'GESTION_COMPRAS', now()
  from portal_aftermarket.compras_gestion_decisiones;
  return v_total;
end;
$$;

-- La versión evita sobrescribir cambios de otro usuario. El lote completo es atómico.
create or replace function portal_aftermarket.compras_gestion_guardar(
  p_cambios jsonb, p_actor text
) returns integer language plpgsql set search_path = '' as $$
declare
  v_cambio jsonb;
  v_sku text;
  v_estado text;
  v_cantidad numeric;
  v_observacion text;
  v_actual portal_aftermarket.compras_gestion_decisiones%rowtype;
  v_total integer;
begin
  if jsonb_typeof(p_cambios) <> 'array' then raise exception 'Cambios inválidos'; end if;
  v_total := jsonb_array_length(p_cambios);
  if v_total < 1 or v_total > 4000 then raise exception 'Cantidad de cambios inválida'; end if;
  if p_actor is null or btrim(p_actor) = '' then raise exception 'Falta responsable'; end if;
  if (select count(distinct upper(btrim(value->>'sku'))) from jsonb_array_elements(p_cambios)) <> v_total then
    raise exception 'Hay SKU duplicados en los cambios';
  end if;
  for v_cambio in select value from jsonb_array_elements(p_cambios) order by value->>'sku' loop
    v_sku := upper(btrim(v_cambio->>'sku'));
    v_estado := v_cambio->>'estadoGestion';
    v_observacion := v_cambio->>'observacion';
    if v_sku = '' or v_estado is null or v_estado not in
      ('PENDIENTE', 'COTIZAR', 'APROBADO', 'NO COMPRAR', 'POSTERGAR', 'ENVIADO A COMPRA') then
      raise exception 'SKU o estado inválido';
    end if;
    if jsonb_typeof(v_cambio->'cantidadDecidida') <> 'number' then raise exception 'Cantidad inválida para %', v_sku; end if;
    v_cantidad := (v_cambio->>'cantidadDecidida')::numeric;
    if v_cantidad < 0 or v_cantidad <> trunc(v_cantidad) then raise exception 'Cantidad inválida para %', v_sku; end if;
    if v_observacion is null or char_length(v_observacion) > 1000 then raise exception 'Observación inválida para %', v_sku; end if;
    if jsonb_typeof(v_cambio->'version') <> 'number' then raise exception 'Versión inválida para %', v_sku; end if;
    select * into v_actual from portal_aftermarket.compras_gestion_decisiones
      where sku = v_sku for update;
    if not found then raise exception 'SKU no migrado: %', v_sku; end if;
    if v_actual.version <> (v_cambio->>'version')::integer then
      raise exception 'La decisión de % cambió. Recargá Gestión antes de guardar.', v_sku;
    end if;
    update portal_aftermarket.compras_gestion_decisiones set
      estado_gestion = v_estado,
      cantidad_decidida = v_cantidad,
      observacion = v_observacion,
      responsable = case when v_estado = 'PENDIENTE' then '' else p_actor end,
      fecha_decision = case when v_estado = 'PENDIENTE' then null else now() end,
      requiere_revision = false,
      version = version + 1,
      actualizado_en = now()
    where sku = v_sku;
    insert into portal_aftermarket.compras_gestion_eventos
      (sku, version, tipo, estado_gestion, cantidad_decidida, observacion, actor)
    values (v_sku, v_actual.version + 1, 'DECISION', v_estado, v_cantidad, v_observacion, p_actor);
  end loop;
  return v_total;
end;
$$;

alter table portal_aftermarket.compras_gestion_decisiones enable row level security;
alter table portal_aftermarket.compras_gestion_eventos enable row level security;
revoke all on portal_aftermarket.compras_gestion_decisiones from public, anon, authenticated;
revoke all on portal_aftermarket.compras_gestion_eventos from public, anon, authenticated;
revoke all on function portal_aftermarket.compras_gestion_importar(jsonb, bigint) from public, anon, authenticated;
revoke all on function portal_aftermarket.compras_gestion_guardar(jsonb, text) from public, anon, authenticated;
grant select, insert, update on portal_aftermarket.compras_gestion_decisiones to service_role;
grant select, insert on portal_aftermarket.compras_gestion_eventos to service_role;
grant execute on function portal_aftermarket.compras_gestion_importar(jsonb, bigint) to service_role;
grant execute on function portal_aftermarket.compras_gestion_guardar(jsonb, text) to service_role;
grant usage, select on all sequences in schema portal_aftermarket to service_role;

commit;
